// ======================================================
// Тестирование API объявлений (aiohttp + SQLAlchemy)
// ======================================================


### 1. Создание нового объявления
POST http://localhost:8080/ads
Content-Type: application/json

{
  "title": "Тестовое объявление",
  "description": "Это тестовое объявление",
  "owner": "Тестовый владелец"
}

> {%
    // Автоматически сохраняем ID созданного объявления для использования в следующих запросах
    client.global.set("ad_id", response.body.id);
%}


### 2. Получение объявления по автоматически сохраненному ID
GET http://localhost:8080/ads/{{ad_id}}


### 3. Получение списка всех объявлений
GET http://localhost:8080/ads


### 4. Полное обновление объявления по ID
PATCH http://localhost:8080/ads/{{ad_id}}
Content-Type: application/json

{
  "title": "Обновленное тестовое объявление",
  "description": "Это объявление было обновлено",
  "owner": "Обновленный владелец"
}


### 5. Получение обновленного объявления (проверка изменений)
GET http://localhost:8080/ads/{{ad_id}}


### 6. Создание объявления с отсутствующими полями (ожидается ошибка 400)
POST http://localhost:8080/ads
Content-Type: application/json

{
  "title": "Неполное объявление"
}


### 7. Получение несуществующего объявления (ожидается ошибка 404)
GET http://localhost:8080/ads/999999


### 8. Создание объявления с пустым описанием (ожидается ошибка 400)
POST http://localhost:8080/ads
Content-Type: application/json

{
  "title": "Тест с пустым описанием",
  "description": "",
  "owner": "Владелец"
}


### 9. Создание объявления со слишком длинным описанием (305 символов, ожидается ошибка 400)
POST http://localhost:8080/ads
Content-Type: application/json

{
  "title": "Тест длинного описания",
  "description": "01234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234",
  "owner": "Владелец"
}


### 10. Частичное обновление (только заголовок)
PATCH http://localhost:8080/ads/{{ad_id}}
Content-Type: application/json

{
  "title": "Новый заголовок"
}


### 11. Частичное обновление (только описание)
PATCH http://localhost:8080/ads/{{ad_id}}
Content-Type: application/json

{
  "description": "Новое описание"
}


### 12. Частичное обновление с пустым owner, состоящим из пробелов (ожидается ошибка 400)
PATCH http://localhost:8080/ads/{{ad_id}}
Content-Type: application/json

{
  "owner": "   "
}


### 13. Обновление несуществующего объявления (ожидается ошибка 404)
PATCH http://localhost:8080/ads/999999
Content-Type: application/json

{
  "title": "Несуществующее"
}


### 14. Удаление конкретного объявления по сохраненному ID
DELETE http://localhost:8080/ads/{{ad_id}}


### 15. Попытка удаления несуществующего объявления (ожидается ошибка 404)
DELETE http://localhost:8080/ads/999999